import ApartmentOutlinedIcon from "@mui/icons-material/ApartmentOutlined";
import HubOutlinedIcon from "@mui/icons-material/HubOutlined";
import DashboardCustomizeOutlinedIcon from "@mui/icons-material/DashboardCustomizeOutlined";
import SupportAgentOutlinedIcon from "@mui/icons-material/SupportAgentOutlined";
import { SolutionCtaContent, SolutionFaqContent, SolutionHeroContent, SolutionIconCard, SolutionTabPanelItem } from "./solution.const";

import imgHero from "assets/img/background/solutions/image-solutions-1.png";
import imgConnected from "assets/img/background/solutions/image-solutions-2.png";
import imgVisibility from "assets/img/background/solutions/image-solutions-3.png";
import imgOutcome from "assets/asyst/img/background/product/overview/background-product.png";
import imgDashboard from "assets/asyst/img/background/product/amala/device-A.png";
import { localized } from "shared/i18n";

// Konten halaman detail solusi (desain revamp 2026). Satu objek per solusi, dirender oleh components/solution/detail.
// Gambar sementara memakai aset yang sudah ada di repo; ganti dengan aset final dari desain.
// Konten dua bahasa: konstanta `...En` = teks EN lengkap; ekspor `localized(...En, {...})` di bawah file = terjemahan ID
// (teks saja, struktur & urutan sama).

export interface SolutionChallengeItem {
    label: string;
    title: string;
    paragraphs: string[];
    solution: { title: string; description: string };
    image: string;
}

export interface SolutionDefinitionItem {
    label: string;
    tag: string;
    title: string;
    description: string;
    pillars: string[];
}

export interface SolutionDetailContent {
    hero: SolutionHeroContent;
    challenge: {
        title: string;
        description: string;
        items: SolutionChallengeItem[];
    };
    definition: {
        title: string;
        description: string;
        items: SolutionDefinitionItem[];
    };
    howItWorks: {
        title: string;
        description: string;
        items: SolutionTabPanelItem[];
    };
    why: {
        title: string;
        items: SolutionIconCard[];
    };
    faq: SolutionFaqContent;
    cta: SolutionCtaContent;
}

const socOurSolution = { title: "Our solution", description: "Connect → Integrate → Orchestrate" };
const socEventOutput = ["Source", "Time", "Asset", "User", "Activity", "Location", "Event Type", "Severity Context"];

// TODO: desain hanya menampilkan isi tab pertama di tiap section bertab; copy tab lain perlu dikonfirmasi
const socDetailEn: SolutionDetailContent = {
    hero: {
        eyebrow: "Security Operation Center",
        title: "Security Operations Center for a More Visible, Resilient Enterprise",
        description: "Security threats can move across infrastructure, applications, networks and digital services. ASYST helps organizations establish a more connected security operations capability through centralized monitoring, security visibility, incident response and integration with enterprise IT operations",
        primaryButton: "Talk to a Security Expert",
        secondaryButton: "Explore Security Capabilities",
        image: imgHero,
    },
    challenge: {
        title: "Security Is No Longer an Isolated IT Function",
        description: "ASYST combines software capability, integration expertise, domain knowledge and long-running enterprise delivery experience to connect technology initiatives with operational needs",
        items: [
            {
                label: "Fragmented Technology",
                title: "Your Business Runs on Systems That Don't Always Work Together",
                paragraphs: [
                    "As organizations grow, technology environments often become increasingly fragmented applications, platforms, infrastructure, data, cloud services, and third-party systems may evolve at different speeds.",
                    "The result is more interfaces to manage, duplicated processes, disconnected data, and limited visibility across the business.",
                ],
                solution: socOurSolution,
                image: imgConnected,
            },
            {
                label: "Limited Visibility",
                title: "Security Events Are Hard to See Across a Distributed Environment",
                paragraphs: [
                    "Security signals are generated by networks, endpoints, applications, cloud services and identity platforms, each with its own tools and logs.",
                    "Without a centralized view, suspicious activity can go unnoticed and security teams spend more time collecting information than acting on it.",
                ],
                solution: socOurSolution,
                image: imgVisibility,
            },
            {
                label: "Technology without Business Outcomes",
                title: "Security Tools Alone Do Not Guarantee Resilience",
                paragraphs: [
                    "Organizations often invest in security technology without connecting it to operational processes, response procedures and business priorities.",
                    "Security becomes measurable when monitoring, response and improvement are tied to the services and operations the business depends on.",
                ],
                solution: socOurSolution,
                image: imgOutcome,
            },
        ],
    },
    definition: {
        title: "What Is a Security Operations Center?",
        description: "A Security Operations Center (SOC) is a centralized function for monitoring, detecting, investigating and responding to security events across an organization's technology environment",
        items: [
            {
                label: "Monitoring",
                tag: "Security Monitoring",
                title: "Continuous Security Visibility",
                description: "Establish centralized visibility across relevant technology environments so security teams can identify events that require attention",
                pillars: ["Network", "Endpoints", "Apps", "Cloud", "Identify", "Devices"],
            },
            {
                label: "Detection",
                tag: "Threat Detection",
                title: "Identify Suspicious Activity Early",
                description: "Correlate security events and compare them against normal activity patterns to surface threats that need investigation",
                pillars: ["Correlation", "Anomalies", "Threat Intel", "Alerts", "Use Cases", "Baselines"],
            },
            {
                label: "Investigation",
                tag: "Security Investigation",
                title: "Understand What Happened and Why",
                description: "Analyze alerts with context from assets, users and activity to determine scope, impact and root cause",
                pillars: ["Context", "Timeline", "Assets", "Users", "Impact", "Root Cause"],
            },
            {
                label: "Response",
                tag: "Incident Response",
                title: "Coordinate a Timely Response",
                description: "Contain and resolve security incidents through defined procedures and coordination with IT and business teams",
                pillars: ["Containment", "Escalation", "Playbooks", "ITSM", "Communication", "Recovery"],
            },
            {
                label: "Improvement",
                tag: "Continuous Improvement",
                title: "Strengthen Security Over Time",
                description: "Use reporting and lessons learned to refine detection, response procedures and the overall security posture",
                pillars: ["Reporting", "Metrics", "Lessons Learned", "Tuning", "Posture", "Compliance"],
            },
        ],
    },
    howItWorks: {
        title: "How Security Operations Work",
        description: "ASYST's recommended SOC operating model connects security signals with enterprise technology operations helping organizations move from security events to actionable response and measurable operational improvement",
        items: [
            {
                label: "Monitor",
                title: "See what is happening across your technology environment",
                description: "Monitoring is the foundation of security operations. The operating model begins by establishing visibility across relevant technology environments and collecting security-relevant signals. A SOC monitoring layer may observe signals from",
                points: ["Collect relevant security events", "Observe system and user activity", "Establish normal activity patterns", "Identify unusual changes", "Maintain visibility across connected environments"],
                subtitle: "Security Event Output:",
                subPoints: socEventOutput,
                image: imgDashboard,
            },
            {
                label: "Detect",
                title: "Recognize events that may indicate a threat",
                description: "Detection turns raw security signals into meaningful alerts by correlating events and comparing them with known threats and normal behaviour.",
                points: ["Correlate events from multiple sources", "Apply detection rules and use cases", "Compare activity with normal patterns", "Generate prioritized alerts"],
                subtitle: "Detection Output:",
                subPoints: ["Alert", "Rule / Use Case", "Related Events", "Affected Asset", "Initial Severity"],
                image: imgDashboard,
            },
            {
                label: "Triage",
                title: "Prioritize what needs attention first",
                description: "Triage validates alerts, filters false positives and assigns priority based on business impact so teams focus on what matters.",
                points: ["Validate alert accuracy", "Filter false positives", "Assess business impact", "Assign priority and owner"],
                subtitle: "Triage Output:",
                subPoints: ["Validated Alert", "Priority", "Owner", "Next Action"],
                image: imgDashboard,
            },
            {
                label: "Investigate",
                title: "Understand the scope and cause of an incident",
                description: "Investigation gathers context across assets, users and activity to understand what happened, how far it spread and why.",
                points: ["Build an incident timeline", "Identify affected assets and users", "Determine root cause", "Assess scope and impact"],
                subtitle: "Investigation Output:",
                subPoints: ["Incident Timeline", "Scope", "Root Cause", "Recommended Action"],
                image: imgDashboard,
            },
            {
                label: "Respond",
                title: "Contain and resolve security incidents",
                description: "Response coordinates containment and remediation with IT operations and business owners through defined procedures.",
                points: ["Contain the threat", "Coordinate with IT and service management", "Remediate affected systems", "Communicate with stakeholders"],
                subtitle: "Response Output:",
                subPoints: ["Containment Action", "Remediation Ticket", "Status Update", "Escalation Record"],
                image: imgDashboard,
            },
            {
                label: "Recover",
                title: "Restore services and normal operations",
                description: "Recovery brings affected services back to normal operation and verifies that the threat has been removed.",
                points: ["Restore affected services", "Verify systems are clean", "Monitor for recurrence", "Confirm business continuity"],
                subtitle: "Recovery Output:",
                subPoints: ["Restored Service", "Verification Result", "Monitoring Status"],
                image: imgDashboard,
            },
            {
                label: "Report",
                title: "Make security performance visible",
                description: "Reporting gives security teams and leadership a clear view of incidents, response performance and security posture.",
                points: ["Summarize incidents and trends", "Track response metrics", "Report to stakeholders", "Support compliance needs"],
                subtitle: "Report Output:",
                subPoints: ["Incident Summary", "Response Metrics", "Trend Analysis", "Compliance Evidence"],
                image: imgDashboard,
            },
            {
                label: "Improve",
                title: "Strengthen security operations continuously",
                description: "Improvement uses lessons learned to tune detection, refine procedures and strengthen the overall security posture.",
                points: ["Capture lessons learned", "Tune detection rules", "Refine response playbooks", "Close security gaps"],
                subtitle: "Improvement Output:",
                subPoints: ["Lessons Learned", "Updated Rules", "Updated Playbooks", "Improvement Plan"],
                image: imgDashboard,
            },
        ],
    },
    why: {
        title: "Why Connect Security Operations With ASYST?",
        items: [
            { icon: ApartmentOutlinedIcon, title: "Enterprise Technology Context", description: "Security can be considered alongside infrastructure, applications, platforms and business systems" },
            { icon: HubOutlinedIcon, title: "Integration Business Capability", description: "Connect security workflows with existing enterprise technology and your business ecosystems and platform" },
            { icon: DashboardCustomizeOutlinedIcon, title: "Operational Digital Experience", description: "ASYST's broader portfolio includes infrastructure and managed services to suit with your business models." },
            { icon: SupportAgentOutlinedIcon, title: "Long-Term Delivery and Support", description: "ASYST describes itself as a technology partner that designs, builds and supports information systems" },
        ],
    },
    faq: {
        title: "Security Operation Center FAQ",
        items: [
            { question: "What is a Security Operations Center?", answer: "A Security Operations Center (SOC) is a centralized security function responsible for monitoring, detecting, investigating and responding to security events" },
            { question: "What does a SOC monitor?", answer: "A SOC monitors security-relevant signals from networks, endpoints, applications, cloud services, identity platforms and devices across the technology environment" },
            { question: "What is the difference between SOC and SIEM?", answer: "A SIEM is a technology platform that collects and correlates security events. A SOC is the operating function — people, processes and technology — that uses tools such as SIEM to monitor, investigate and respond" },
            { question: "Does a SOC respond to security incidents?", answer: "Yes. Beyond monitoring and detection, a SOC coordinates triage, investigation, containment and recovery of security incidents together with IT and business teams" },
            { question: "Can SOC integrate with ITSM?", answer: "Yes. Integrating SOC with IT service management allows security incidents to flow into existing ticketing, escalation and remediation processes" },
            { question: "Can ASYST integrate security operations with enterprise IT?", answer: "Yes. ASYST connects security operations with infrastructure, applications, platforms and service management so security is handled as part of enterprise IT operations" },
        ],
    },
    cta: {
        title: "Your Security Environment Is Only as Strong as Your Visibility and Response",
        description: "Talk to ASYST about your current security monitoring, IT environment, integration landscape and operational requirements",
        button: "Talk to Security Expert",
    },
}

// ---------- terjemahan ID (struktur & urutan sama dengan socDetailEn) ----------

const socOurSolutionId = { title: "Solusi kami", description: "Hubungkan → Integrasikan → Orkestrasikan" };
const socEventOutputId = ["Sumber", "Waktu", "Aset", "Pengguna", "Aktivitas", "Lokasi", "Jenis Event", "Konteks Tingkat Keparahan"];

export const SocDetailConst = localized(socDetailEn, {
    hero: {
        eyebrow: "Security Operation Center",
        title: "Security Operations Center untuk Perusahaan yang Lebih Terpantau dan Tangguh",
        description: "Ancaman keamanan dapat bergerak di seluruh infrastruktur, aplikasi, jaringan, dan layanan digital. ASYST membantu organisasi membangun kapabilitas operasional keamanan yang lebih terhubung melalui pemantauan terpusat, visibilitas keamanan, respons insiden, dan integrasi dengan operasional IT enterprise",
        primaryButton: "Hubungi Ahli Keamanan",
        secondaryButton: "Jelajahi Kapabilitas Keamanan",
    },
    challenge: {
        title: "Keamanan Bukan Lagi Fungsi IT yang Berdiri Sendiri",
        description: "ASYST memadukan kapabilitas software, keahlian integrasi, pengetahuan domain, dan pengalaman delivery enterprise jangka panjang untuk menghubungkan inisiatif teknologi dengan kebutuhan operasional",
        items: [
            {
                label: "Teknologi Terfragmentasi",
                title: "Bisnis Anda Berjalan di Atas Sistem yang Tidak Selalu Saling Terhubung",
                paragraphs: [
                    "Seiring pertumbuhan organisasi, lingkungan teknologi sering menjadi semakin terfragmentasi: aplikasi, platform, infrastruktur, data, layanan cloud, dan sistem pihak ketiga dapat berkembang dengan kecepatan yang berbeda.",
                    "Akibatnya, semakin banyak antarmuka yang harus dikelola, proses yang tumpang tindih, data yang terputus, dan visibilitas yang terbatas di seluruh bisnis.",
                ],
                solution: socOurSolutionId,
            },
            {
                label: "Visibilitas Terbatas",
                title: "Event Keamanan Sulit Terlihat di Lingkungan yang Tersebar",
                paragraphs: [
                    "Sinyal keamanan dihasilkan oleh jaringan, endpoint, aplikasi, layanan cloud, dan platform identitas, masing-masing dengan tools dan log-nya sendiri.",
                    "Tanpa tampilan terpusat, aktivitas mencurigakan dapat luput dari perhatian dan tim keamanan menghabiskan lebih banyak waktu mengumpulkan informasi daripada bertindak.",
                ],
                solution: socOurSolutionId,
            },
            {
                label: "Teknologi tanpa Hasil Bisnis",
                title: "Tools Keamanan Saja Tidak Menjamin Ketahanan",
                paragraphs: [
                    "Organisasi sering berinvestasi pada teknologi keamanan tanpa menghubungkannya dengan proses operasional, prosedur respons, dan prioritas bisnis.",
                    "Keamanan menjadi terukur ketika pemantauan, respons, dan perbaikan dikaitkan dengan layanan dan operasional yang diandalkan bisnis.",
                ],
                solution: socOurSolutionId,
            },
        ],
    },
    definition: {
        title: "Apa Itu Security Operations Center?",
        description: "Security Operations Center (SOC) adalah fungsi terpusat untuk memantau, mendeteksi, menyelidiki, dan merespons event keamanan di seluruh lingkungan teknologi organisasi",
        items: [
            {
                label: "Pemantauan",
                tag: "Pemantauan Keamanan",
                title: "Visibilitas Keamanan Berkelanjutan",
                description: "Bangun visibilitas terpusat di seluruh lingkungan teknologi yang relevan agar tim keamanan dapat mengidentifikasi event yang perlu ditangani",
                pillars: ["Jaringan", "Endpoint", "Aplikasi", "Cloud", "Identitas", "Perangkat"],
            },
            {
                label: "Deteksi",
                tag: "Deteksi Ancaman",
                title: "Identifikasi Aktivitas Mencurigakan Sejak Dini",
                description: "Korelasikan event keamanan dan bandingkan dengan pola aktivitas normal untuk memunculkan ancaman yang perlu diselidiki",
                pillars: ["Korelasi", "Anomali", "Threat Intel", "Alert", "Use Case", "Baseline"],
            },
            {
                label: "Investigasi",
                tag: "Investigasi Keamanan",
                title: "Pahami Apa yang Terjadi dan Mengapa",
                description: "Analisis alert dengan konteks aset, pengguna, dan aktivitas untuk menentukan cakupan, dampak, dan akar masalah",
                pillars: ["Konteks", "Timeline", "Aset", "Pengguna", "Dampak", "Akar Masalah"],
            },
            {
                label: "Respons",
                tag: "Respons Insiden",
                title: "Koordinasikan Respons Tepat Waktu",
                description: "Tahan dan selesaikan insiden keamanan melalui prosedur yang ditetapkan serta koordinasi dengan tim IT dan bisnis",
                pillars: ["Penahanan", "Eskalasi", "Playbook", "ITSM", "Komunikasi", "Pemulihan"],
            },
            {
                label: "Perbaikan",
                tag: "Perbaikan Berkelanjutan",
                title: "Perkuat Keamanan dari Waktu ke Waktu",
                description: "Gunakan pelaporan dan pembelajaran untuk menyempurnakan deteksi, prosedur respons, dan postur keamanan secara keseluruhan",
                pillars: ["Pelaporan", "Metrik", "Pembelajaran", "Penyetelan", "Postur", "Kepatuhan"],
            },
        ],
    },
    howItWorks: {
        title: "Bagaimana Operasional Keamanan Bekerja",
        description: "Model operasional SOC yang direkomendasikan ASYST menghubungkan sinyal keamanan dengan operasional teknologi enterprise, membantu organisasi bergerak dari event keamanan menuju respons yang dapat ditindaklanjuti dan peningkatan operasional yang terukur",
        items: [
            {
                label: "Pantau",
                title: "Lihat apa yang terjadi di lingkungan teknologi Anda",
                description: "Pemantauan adalah fondasi operasional keamanan. Model operasional dimulai dengan membangun visibilitas di seluruh lingkungan teknologi yang relevan dan mengumpulkan sinyal yang berkaitan dengan keamanan. Lapisan pemantauan SOC dapat mengamati sinyal dari",
                points: ["Mengumpulkan event keamanan yang relevan", "Mengamati aktivitas sistem dan pengguna", "Menetapkan pola aktivitas normal", "Mengidentifikasi perubahan yang tidak biasa", "Menjaga visibilitas di seluruh lingkungan yang terhubung"],
                subtitle: "Output Event Keamanan:",
                subPoints: socEventOutputId,
            },
            {
                label: "Deteksi",
                title: "Kenali event yang mungkin mengindikasikan ancaman",
                description: "Deteksi mengubah sinyal keamanan mentah menjadi alert yang bermakna dengan mengorelasikan event dan membandingkannya dengan ancaman yang diketahui dan perilaku normal.",
                points: ["Mengorelasikan event dari berbagai sumber", "Menerapkan aturan deteksi dan use case", "Membandingkan aktivitas dengan pola normal", "Menghasilkan alert yang diprioritaskan"],
                subtitle: "Output Deteksi:",
                subPoints: ["Alert", "Aturan / Use Case", "Event Terkait", "Aset Terdampak", "Tingkat Keparahan Awal"],
            },
            {
                label: "Triase",
                title: "Prioritaskan yang perlu ditangani lebih dulu",
                description: "Triase memvalidasi alert, menyaring false positive, dan menetapkan prioritas berdasarkan dampak bisnis agar tim fokus pada hal yang penting.",
                points: ["Memvalidasi akurasi alert", "Menyaring false positive", "Menilai dampak bisnis", "Menetapkan prioritas dan penanggung jawab"],
                subtitle: "Output Triase:",
                subPoints: ["Alert Tervalidasi", "Prioritas", "Penanggung Jawab", "Tindakan Berikutnya"],
            },
            {
                label: "Investigasi",
                title: "Pahami cakupan dan penyebab insiden",
                description: "Investigasi mengumpulkan konteks dari aset, pengguna, dan aktivitas untuk memahami apa yang terjadi, seberapa luas penyebarannya, dan mengapa.",
                points: ["Menyusun timeline insiden", "Mengidentifikasi aset dan pengguna terdampak", "Menentukan akar masalah", "Menilai cakupan dan dampak"],
                subtitle: "Output Investigasi:",
                subPoints: ["Timeline Insiden", "Cakupan", "Akar Masalah", "Tindakan yang Direkomendasikan"],
            },
            {
                label: "Respons",
                title: "Tahan dan selesaikan insiden keamanan",
                description: "Respons mengoordinasikan penahanan dan remediasi bersama operasional IT dan pemilik bisnis melalui prosedur yang ditetapkan.",
                points: ["Menahan ancaman", "Berkoordinasi dengan IT dan manajemen layanan", "Meremediasi sistem terdampak", "Berkomunikasi dengan stakeholder"],
                subtitle: "Output Respons:",
                subPoints: ["Tindakan Penahanan", "Tiket Remediasi", "Pembaruan Status", "Catatan Eskalasi"],
            },
            {
                label: "Pulihkan",
                title: "Pulihkan layanan dan operasional normal",
                description: "Pemulihan mengembalikan layanan terdampak ke operasional normal dan memverifikasi bahwa ancaman telah dihilangkan.",
                points: ["Memulihkan layanan terdampak", "Memverifikasi sistem sudah bersih", "Memantau kemungkinan terulang", "Memastikan kelangsungan bisnis"],
                subtitle: "Output Pemulihan:",
                subPoints: ["Layanan Pulih", "Hasil Verifikasi", "Status Pemantauan"],
            },
            {
                label: "Laporkan",
                title: "Tampilkan kinerja keamanan secara transparan",
                description: "Pelaporan memberi tim keamanan dan pimpinan gambaran yang jelas tentang insiden, kinerja respons, dan postur keamanan.",
                points: ["Merangkum insiden dan tren", "Memantau metrik respons", "Melapor kepada stakeholder", "Mendukung kebutuhan kepatuhan"],
                subtitle: "Output Laporan:",
                subPoints: ["Ringkasan Insiden", "Metrik Respons", "Analisis Tren", "Bukti Kepatuhan"],
            },
            {
                label: "Tingkatkan",
                title: "Perkuat operasional keamanan secara berkelanjutan",
                description: "Peningkatan memanfaatkan pembelajaran untuk menyetel deteksi, menyempurnakan prosedur, dan memperkuat postur keamanan secara keseluruhan.",
                points: ["Mencatat pembelajaran", "Menyetel aturan deteksi", "Menyempurnakan playbook respons", "Menutup celah keamanan"],
                subtitle: "Output Peningkatan:",
                subPoints: ["Pembelajaran", "Aturan Diperbarui", "Playbook Diperbarui", "Rencana Peningkatan"],
            },
        ],
    },
    why: {
        title: "Mengapa Menghubungkan Operasional Keamanan dengan ASYST?",
        items: [
            { title: "Konteks Teknologi Enterprise", description: "Keamanan dapat dipertimbangkan bersama infrastruktur, aplikasi, platform, dan sistem bisnis" },
            { title: "Kapabilitas Integrasi Bisnis", description: "Hubungkan alur kerja keamanan dengan teknologi enterprise yang ada serta ekosistem dan platform bisnis Anda" },
            { title: "Pengalaman Digital Operasional", description: "Portofolio ASYST yang lebih luas mencakup infrastruktur dan layanan terkelola yang dapat disesuaikan dengan model bisnis Anda." },
            { title: "Delivery dan Dukungan Jangka Panjang", description: "ASYST adalah mitra teknologi yang merancang, membangun, dan mendukung sistem informasi" },
        ],
    },
    faq: {
        title: "FAQ Security Operation Center",
        items: [
            { question: "Apa itu Security Operations Center?", answer: "Security Operations Center (SOC) adalah fungsi keamanan terpusat yang bertanggung jawab memantau, mendeteksi, menyelidiki, dan merespons event keamanan" },
            { question: "Apa yang dipantau oleh SOC?", answer: "SOC memantau sinyal terkait keamanan dari jaringan, endpoint, aplikasi, layanan cloud, platform identitas, dan perangkat di seluruh lingkungan teknologi" },
            { question: "Apa perbedaan SOC dan SIEM?", answer: "SIEM adalah platform teknologi yang mengumpulkan dan mengorelasikan event keamanan. SOC adalah fungsi operasional — orang, proses, dan teknologi — yang menggunakan tools seperti SIEM untuk memantau, menyelidiki, dan merespons" },
            { question: "Apakah SOC merespons insiden keamanan?", answer: "Ya. Selain pemantauan dan deteksi, SOC mengoordinasikan triase, investigasi, penahanan, dan pemulihan insiden keamanan bersama tim IT dan bisnis" },
            { question: "Apakah SOC dapat terintegrasi dengan ITSM?", answer: "Ya. Integrasi SOC dengan manajemen layanan IT memungkinkan insiden keamanan masuk ke proses ticketing, eskalasi, dan remediasi yang sudah ada" },
            { question: "Apakah ASYST dapat mengintegrasikan operasional keamanan dengan IT enterprise?", answer: "Ya. ASYST menghubungkan operasional keamanan dengan infrastruktur, aplikasi, platform, dan manajemen layanan sehingga keamanan ditangani sebagai bagian dari operasional IT enterprise" },
        ],
    },
    cta: {
        title: "Kekuatan Lingkungan Keamanan Anda Bergantung pada Visibilitas dan Respons",
        description: "Diskusikan pemantauan keamanan, lingkungan IT, lanskap integrasi, dan kebutuhan operasional Anda saat ini bersama ASYST",
        button: "Hubungi Ahli Keamanan",
    },
});
